    version: '3.8'

    services:
        main:
            build: .
            entrypoint: tail -f /dev/null
            volumes:
                #This will map your dev environment into the container so you
                #won't need to rebuild the container at each code change. It will map
                #the entire project so if you use VS Code yu will be able to attach to
                #the container and use Git-related resources.
                - .:/work
                #This is so the image can have the same git rights as the host.
                #Otherwise MLFLOW won't be able to track commits.
                - ${HOST_SSH_KEYS_DIR?err}:/root/.ssh
            environment:
                PYTHONPATH: ${PYTHONPATH?err}
                LPSDS_BUCKET: ${LPSDS_BUCKET?err}
                LPSDS_HANDLER: ${LPSDS_HANDLER?err}
